import { baseConfig } from './wdio.base.conf.js';

export const config = {
    ...baseConfig,
    specs: [
        '../../tests/e2e/app-startup.spec.ts',
        '../../tests/e2e/first-run.spec.ts',
        '../../tests/e2e/auto-update-init.spec.ts',
        '../../tests/e2e/window.spec.ts',
        '../../tests/e2e/menu.spec.ts',
        '../../tests/e2e/hotkeys.spec.ts',
        '../../tests/e2e/quick-chat.spec.ts',
        '../../tests/e2e/quick-chat-full-workflow.spec.ts',
        '../../tests/e2e/options-window.spec.ts',
        '../../tests/e2e/options-tabs.spec.ts',
        '../../tests/e2e/settings-persistence.spec.ts',
        '../../tests/e2e/theme.spec.ts',
        '../../tests/e2e/auth.spec.ts',
        '../../tests/e2e/oauth-links.spec.ts',
        '../../tests/e2e/external-links.spec.ts',
        '../../tests/e2e/tray.spec.ts',
        '../../tests/e2e/tray-quit.spec.ts',
        '../../tests/e2e/minimize-to-tray.spec.ts',
        '../../tests/e2e/auto-update.spec.ts',
        '../../tests/e2e/toast.spec.ts',
        '../../tests/e2e/fatal-error-recovery.spec.ts',
        '../../tests/e2e/offline-behavior.spec.ts',
        '../../tests/e2e/session-persistence.spec.ts',
        '../../tests/e2e/single-instance.spec.ts',
        '../../tests/e2e/webview-content.spec.ts',
        '../../tests/e2e/macos-dock.spec.ts',
        '../../tests/e2e/macos-menu.spec.ts',
        '../../tests/e2e/macos-window-behavior.spec.ts',
        '../../tests/e2e/microphone-permission.spec.ts',
    ],
};
